# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.27.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    4,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"x\n\x04user\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\x12\x17\n\x08usertype\x18\x06 \x01(\x0e\x32\x05.Type\x12\x18\n\x04type\x18\x07 \x01(\x0e\x32\n.Operation*\x1f\n\x04Type\x12\t\n\x05\x41\x44MIN\x10\x00\x12\x0c\n\x08\x43USTOMER\x10\x01*8\n\tOperation\x12\n\n\x06UNKWON\x10\x00\x12\n\n\x06\x43REATE\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02\x12\x07\n\x03PUT\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TYPE']._serialized_start=136
  _globals['_TYPE']._serialized_end=167
  _globals['_OPERATION']._serialized_start=169
  _globals['_OPERATION']._serialized_end=225
  _globals['_USER']._serialized_start=14
  _globals['_USER']._serialized_end=134
# @@protoc_insertion_point(module_scope)
